// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ogrenc.DataAccess;

#nullable disable

namespace Ogrenc.DataAccess.Migrations
{
    [DbContext(typeof(OgrenciDbContext))]
    [Migration("20220211013410_x1")]
    partial class x1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ogrenc.Entities.Bolum", b =>
                {
                    b.Property<int>("IdBolum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBolum"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdBolum");

                    b.ToTable("Bolums");
                });

            modelBuilder.Entity("Ogrenc.Entities.Ogrenci", b =>
                {
                    b.Property<int>("IdOgrenci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOgrenci"), 1L, 1);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AnaDalId")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YanDalId")
                        .HasColumnType("int");

                    b.HasKey("IdOgrenci");

                    b.HasIndex("AnaDalId");

                    b.HasIndex("YanDalId");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("Ogrenc.Entities.Ogrenci", b =>
                {
                    b.HasOne("Ogrenc.Entities.Bolum", "Anadal")
                        .WithMany("AnaDalOgrencileri")
                        .HasForeignKey("AnaDalId");

                    b.HasOne("Ogrenc.Entities.Bolum", "Yandal")
                        .WithMany("YanDalOgrencileri")
                        .HasForeignKey("YanDalId");

                    b.Navigation("Anadal");

                    b.Navigation("Yandal");
                });

            modelBuilder.Entity("Ogrenc.Entities.Bolum", b =>
                {
                    b.Navigation("AnaDalOgrencileri");

                    b.Navigation("YanDalOgrencileri");
                });
#pragma warning restore 612, 618
        }
    }
}
