// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ogrenc.DataAccess;

#nullable disable

namespace Ogrenc.DataAccess.Migrations
{
    [DbContext(typeof(OgrenciDbContext))]
    partial class OgrenciDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ogrenc.Entities.Ders", b =>
                {
                    b.Property<int>("IdDers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDers"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDers");

                    b.ToTable("Derss");
                });

            modelBuilder.Entity("Ogrenc.Entities.DonemDersleri", b =>
                {
                    b.Property<int>("IdDonem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonem"), 1L, 1);

                    b.Property<int?>("DersIdDers")
                        .HasColumnType("int");

                    b.Property<string>("Donem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OgrenciIdOgrenci")
                        .HasColumnType("int");

                    b.HasKey("IdDonem");

                    b.HasIndex("DersIdDers");

                    b.HasIndex("OgrenciIdOgrenci");

                    b.ToTable("DonemDersleris");
                });

            modelBuilder.Entity("Ogrenc.Entities.Ogrenci", b =>
                {
                    b.Property<int>("IdOgrenci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOgrenci"), 1L, 1);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOgrenci");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("Ogrenc.Entities.DonemDersleri", b =>
                {
                    b.HasOne("Ogrenc.Entities.Ders", null)
                        .WithMany("DonemDersleris")
                        .HasForeignKey("DersIdDers");

                    b.HasOne("Ogrenc.Entities.Ogrenci", null)
                        .WithMany("DonemDersleris")
                        .HasForeignKey("OgrenciIdOgrenci");
                });

            modelBuilder.Entity("Ogrenc.Entities.Ders", b =>
                {
                    b.Navigation("DonemDersleris");
                });

            modelBuilder.Entity("Ogrenc.Entities.Ogrenci", b =>
                {
                    b.Navigation("DonemDersleris");
                });
#pragma warning restore 612, 618
        }
    }
}
